const sidebars = {
  
  htmap: [
    {
      type: 'category',
      label: 'Creating Plugins',
      items: [
        {
          type: 'autogenerated',
          dirName: 'htmap', 
        },
      ],
    },
  ],
  formapi: [
    {
      type: 'category',
      label: 'FormAPI',
      items: [
        {
          type: 'autogenerated',
          dirName: 'form-api', 
        },
      ],
    },
  ],
  bedrockeconomy: [
    {
      type: 'category',
      label: 'Bedrock Economy',
      items: [
        {
          type: 'autogenerated',
          dirName: 'bedrock-economy', 
        },
      ],
    },
  ],

};

module.exports = sidebars;