const sidebars = {
  
  htmap: [
    {
      type: 'autogenerated', 
      dirName: 'htmap',
    }
  ],
  formapi: [
    {
      type: 'autogenerated', 
      dirName: 'form-api',
    }
  ],

};

module.exports = sidebars;